### ISSUE TITLE
Future issue? Kernel 6.9.2 Ethernet Issue

### ISSUE THREAD

**Issue by StarLordRammi** [Nobara-Project/nobara-core-packages#12]
Hi, im new to Linux and been trying different distros. I noticed that on new Arch distros which have 6.9.2 Kernel, my ethernet doesn't work and looking around in forums for those distros other people have same issues. my ethernet is RTL8125 2.5G (x570 Tomahawk Wifi). my question is, when Nobara is updated to that Kernel version, will I face the same issue? 

Realtek RTL8125 2.5GbE

Kernel 6.9.2 installs driver version: r8169 which doesn't work with RTL8125 for some reason.

**Comment by GloriousEggroll** [comment]
We follow fedora's kernel releases generally. Arch is bleeding edge in terms of the kernel. If the issue arises by the time we migrate to 6.9 I'll repopen this, but generally fedora is pretty good at getting things like that patched before they release. Closing for now.
