### ISSUE TITLE
INSTALL Proton-GE does nothing.

### ISSUE THREAD

**Issue by Andy91xx** [Nobara-Project/nobara-core-packages#13]
as the title describes when i click install nothing happens  im new to linux so unsure if could install it manually correctly or if i even need it .

**Comment by GloriousEggroll** [comment]
Thanks for the heads up -- this is due to a change from using protonup-qt to protonplus. In your application menu search for protonplus and you should be able to install it that way. I'll push a fix for the welcome app button shortly.

**Comment by GloriousEggroll** [comment]
should be resolved now with:

https://github.com/Nobara-Project/nobara-core-packages/commit/152de1c2a2c0028b6a87951488aa49243dbfb888

run Update System then reopen the welcome app
