### ISSUE TITLE
incompatible vnidi drivers

### ISSUE THREAD

**Issue by diimku** [Nobara-Project/nobara-core-packages#16]
Drivers are incompatible in my case. from nvidia site is NVIDIA-Linux-x86_64-470.63.01 Can you pls added in the nest update? ty

**Comment by GloriousEggroll** [comment]
> Drivers are incompatible in my case. from nvidia site is NVIDIA-Linux-x86_64-470.63.01 Can you pls added in the nest update? ty

We only provide the latest driver and do not support cards that are not supported by the latest driver:

https://nobaraproject.org/docs/nvidia-troubleshooting/supported-hardware/
