### ISSUE TITLE
Unable to do anything with flatpaks in Nobara Package Manager

### ISSUE THREAD

**Issue by soKKett** [Nobara-Project/nobara-core-packages#19]
When i click on 'delete' or 'update', or 'install' buttons - there is a notification, that says 'interrupted by user' (in russian), so nothing happens

![Снимок экрана_20240801_195812](https://github.com/user-attachments/assets/7fbbd7c9-7fd4-44db-85d1-580e1679e414)

**Comment by GloriousEggroll** [comment]
> can you provide the most recent traceback file in ~/.local/share/yumex ?
> can you try changing the locale to en_US?
