### ISSUE TITLE
Nobara dark GTK theme is completely transparent in Flatpak's when using another distro.

### ISSUE THREAD

**Issue by agoodfellow123** [Nobara-Project/nobara-core-packages#21]
Hi, first of all, I'm not on Nobara. I'm using Manjaro at the moment. I cloned this repo got kde-nobara folder, copied the files in `/usr/share/` to my `/usr/share` and also copied `/usr/share/themes/Nobara` to `~/.themes`. For good measure, I installed the Breeze and Breeze-dark themes in Flatpak. When I set `GTK_THEME=Nobara` I get the light theme no problem. However, when set to `GTK_THEME=Nobara:dark` all the Flatpak GTK applications become completely transparent. I can use similar themes such as "materia-blackout" for GTK, but I really like the Nobara theme and constancy between QT and GTK themes. Can this be solved.

Here is how it looks:
![image](https://github.com/user-attachments/assets/59ec0c1f-cd15-4855-80f3-c7c94c422a85)

Edit: Just realized, this problem applies to system GTK theme as well. Also, this used to work on older versions of kde-nobara.

**Comment by GloriousEggroll** [comment]
Running the Nobara theme outside of Nobara is not supported. Many of the files modified for the theme are done on the system level which will not work in ~/.themes, additionally there are scripts and configurations shipped in the rpm which are applied on login and needed.

If you have issues with the Nobara theme when running it in Nobara using the rpm for installation I'd be happy to take a further look.
