### ISSUE TITLE
Feature Request: Add ZLUDA to the Nobara Driver Manager as an optional install

### ISSUE THREAD

**Issue by mateowoetam** [Nobara-Project/nobara-core-packages#3]
Description:

I would like to request the addition of [ZLUDA](https://github.com/vosen/ZLUDA) as an optional installable component within the Nobara Driver Manager for AMD GPUs. "ZLUDA lets you run unmodified CUDA applications with near-native performance on Intel AMD GPUs." (project is alpha but it might be good to consider this for when the full release is out)

Benefits:

Including ZLUDA in the Nobara Driver Manager would provide several benefits to users, including:

- Simplified installation process: Having ZLUDA available through the Driver Manager would streamline the installation process for users who need it, eliminating the need to search for and download it from external sources.
- Improved system compatibility: Integrating ZLUDA with the Driver Manager would ensure a wider range of software compatability with the Nobara system.
- Increased discoverability: Many users might not be aware of ZLUDA's existence or its potential benefits. Including it in the Driver Manager would raise awareness and make it easily discoverable for those who could benefit from it.

**Comment by matte-schwartz** [comment]
I did take a look into this and unfortunately it seems like the version of ROCm we ship, 6, is incompatible with ZLUDA: https://github.com/vosen/ZLUDA/blob/master/README.md#build

**Comment by GloriousEggroll** [comment]
closing as zluda is not compatible with rocm 6. open for consideration if that changes
