### ISSUE TITLE
Amd Rocm failed to verify checksum

### ISSUE THREAD

**Issue by saigauthamr** [Nobara-Project/nobara-core-packages#30]
I have an amd radeon Rx7900XTX. While trying to install the ROCm driver, I am getting an issue. I am posting the log below.

package rocm-meta is not installed
nobara-rocm-official                             69 kB/s | 3.0 kB     00:00    
Dependencies resolved.
=========================================================================================
 Package                   Arch    Version                    Repository             Size
=========================================================================================
Installing:
 rocm-meta                 x86_64  6.2.4-1.copr.fc40          nobara-baseos-40      8.7 k
Installing dependencies:
 comgr                     x86_64  2.8.0.60204-139.el9        nobara-rocm-official   51 M
 hip-runtime-amd           x86_64  6.2.41134.60204-139.el9    nobara-rocm-official   12 M
 hsa-rocr                  x86_64  1.14.0.60204-139.el9       nobara-rocm-official  797 k
 openmp-extras-runtime     x86_64  18.62.0.60204-139.el9      nobara-rocm-official  131 M
 python-setuptools-wheel   noarch  69.0.3-4.fc40              updates               677 k
 python3.9                 x86_64  3.9.20-1.fc40              updates                19 M
 rocm-device-libs          x86_64  1.0.0.60204-139.el9        nobara-rocm-official  628 k
 rocm-hip-runtime          x86_64  6.2.4.60204-139.el9        nobara-rocm-official   10 k
 rocm-language-runtime     x86_64  6.2.4.60204-139.el9        nobara-rocm-official  7.2 k
 rocm-llvm                 x86_64  18.0.0.24392.60204-139.el9 nobara-rocm-official  277 M
 rocm-opencl               x86_64  2.0.0.60204-139.el9        nobara-rocm-official  619 k
 rocm-opencl-runtime       x86_64  6.2.4.60204-139.el9        nobara-rocm-official   10 k
 rocm-smi-lib              x86_64  7.3.0.60204-139.el9        nobara-rocm-official  685 k
 rocminfo                  x86_64  1.0.0.60204-139.el9        nobara-rocm-official   39 k
 rocprofiler-register      x86_64  0.4.0.60204-139.el9        nobara-rocm-official  301 k

Transaction Summary
=========================================================================================
Install  16 Packages

Total size: 494 M
Total download size: 429 M
Installed size: 1.5 G
Downloading Packages:
[SKIPPED] rocm-meta-6.2.4-1.copr.fc40.x86_64.rpm: Already downloaded           
[SKIPPED] comgr-2.8.0.60204-139.el9.x86_64.rpm: Already downloaded             
[SKIPPED] hip-runtime-amd-6.2.41134.60204-139.el9.x86_64.rpm: Already downloaded
[SKIPPED] hsa-rocr-1.14.0.60204-139.el9.x86_64.rpm: Already downloaded         
[SKIPPED] rocm-device-libs-1.0.0.60204-139.el9.x86_64.rpm: Already downloaded  
[SKIPPED] rocm-hip-runtime-6.2.4.60204-139.el9.x86_64.rpm: Already downloaded  
[SKIPPED] rocm-language-runtime-6.2.4.60204-139.el9.x86_64.rpm: Already downloaded
[SKIPPED] python-setuptools-wheel-69.0.3-4.fc40.noarch.rpm: Already downloaded 
[MIRROR] rocm-opencl-2.0.0.60204-139.el9.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: f53566f50b29eb968fe02db256f785281fbfd31bc9aca50012da42bb30255c6c(sha256)  Expected: 0be5ae7c8a3331ec13c36cf5f38ab065074e37eaefe37d15470a2095b36d2670(sha256) 
[MIRROR] rocm-opencl-2.0.0.60204-139.el9.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: f53566f50b29eb968fe02db256f785281fbfd31bc9aca50012da42bb30255c6c(sha256)  Expected: 0be5ae7c8a3331ec13c36cf5f38ab065074e37eaefe37d15470a2095b36d2670(sha256) 
[MIRROR] rocm-opencl-2.0.0.60204-139.el9.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: f53566f50b29eb968fe02db256f785281fbfd31bc9aca50012da42bb30255c6c(sha256)  Expected: 0be5ae7c8a3331ec13c36cf5f38ab065074e37eaefe37d15470a2095b36d2670(sha256) 
[MIRROR] rocm-opencl-2.0.0.60204-139.el9.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: f53566f50b29eb968fe02db256f785281fbfd31bc9aca50012da42bb30255c6c(sha256)  Expected: 0be5ae7c8a3331ec13c36cf5f38ab065074e37eaefe37d15470a2095b36d2670(sha256) 
[FAILED] rocm-opencl-2.0.0.60204-139.el9.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  rocm-opencl-2.0.0.60204-139.el9.x86_64: Cannot download, all mirrors were already tried without success

**Comment by GloriousEggroll** [comment]
no problems here. check your download cache and/or clear it.

It's saying you already have the package downloaded:
```
[MIRROR] rocm-opencl-2.0.0.60204-139.el9.x86_64.rpm: Downloading successful, 
```
But the checksum of the downloaded file doesn't match what it's supposed to be:
```
but checksum doesn't match. 
Calculated: f53566f50b29eb968fe02db256f785281fbfd31bc9aca50012da42bb30255c6c(sha256) 
Expected: 0be5ae7c8a3331ec13c36cf5f38ab065074e37eaefe37d15470a2095b36d2670(sha256)
```
So either your download got corrupted or interrupted somehow.

It's installed fine on my system. Additionally we do not provide any mirror of the rocm repository, we ship AMD's official repository directly. So there is no middle-man from our side.
