### ISSUE TITLE
Remove icon themes as a dependency

### ISSUE THREAD

**Issue by superuser-does** [Nobara-Project/nobara-core-packages#4]
I use Nobara KDE. I had a very difficult time upgrading to version 39, and again when Nobara changed to KDE6. This is with a whopping 41GB partition and no data, only a few packages + flatpak (which is quite large but a practical necessity for some packages).

With that background:
The papirus icon theme that `nobara-nvidia-wizard` requires in particular is over 500MB in size. These can make a distro upgrade fail. As such, I wonder if the programming can change to reuse whichever freedesktop icon theme is available (e.g. Breeze will be installed by default on Nobara KDE), without requiring this additional dependency. Thank you for your consideration.

**Comment by GloriousEggroll** [comment]
Sorry but we intentionally use papyrus as the icon theme for the launcher and do not intend to change it. It is also required for Nobara Official's default theme.
