### ISSUE TITLE
Nobara Welcome App - "No Internet Connection"

### ISSUE THREAD

**Issue by CyberTeckyLLC** [Nobara-Project/nobara-core-packages#6]
Greetings!

As of today, a repetitive pop-up error that states, "no internet connection" appears to have returned while running the 'Nobara Welcome App' even though internet access is GOOD.  I recall seeing this particular error only after installing 'Nobara Linux 39' for the first time (e.g., Jan 24').  The following fix/solution resolved the issue, however, the "no internet connection" has returned and seems to ignore the original solution:

**ORIGINAL FIX/SOLUTION**
Edited/Changed the spider URL to 'http://ddg.gg' from Line 7 in 'flatpak-install.sh' and 'pkcon-install.sh' bash scripts [See REF. A]:

- [ ] REF. A   |   wget -q --spider http://ddg.gg

NOTE - I'm not sure if this is relevant, but all the default scripts normally found in the 'nobara-welcome' directory were missing, and I'm wondering if the latest updates today (April 4th, 2024) had anything to do with it?  One thing is for sure, I could NOT run the Nobara 'Update System' tool until restoring the 'nobara-welcome' directory from backup.

Hope this helps...

_TheCyberTecky_

**Comment by incrazyboyy** [comment]
I have the same problem on the Nobara 39 Gnome install I did today. The version is 5.0.0. The blue "Application locked" banner stays for like 30s, disappears for a few seconds, and then comes back again. I can click stuff if I get the timing right lol

**Comment by GloriousEggroll** [comment]
resolved https://github.com/Nobara-Project/nobara-core-packages/commit/3bbddd51067000c3f3967c270e49b0d57d50d105
