### ISSUE TITLE
Nobara Driver Manager shows Network Error but I can use the network

### ISSUE THREAD

**Issue by Khaos1221** [Nobara-Project/nobara-core-packages#9]
![image](https://github.com/Nobara-Project/nobara-core-packages/assets/153202880/d740547f-af7f-4ee7-b1d0-59cdd7e144fd)
This is occuring NObara welcome app too

I am new to nobara but this is a bit irritating

**Comment by GloriousEggroll** [comment]
should be resolved by d7f248e287e1c1a4a89826afba4a78326f8dd724
